#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-saxon
Version  : 9.8.0.12
Release  : 2
URL      : https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12-sources.jar
Source0  : https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12-sources.jar
Source1  : https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.jar
Source2  : https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-1.0
Requires: mvn-saxon-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-saxon package.
Group: Data

%description data
data components for the mvn-saxon package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12-sources.jar
/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.jar
/usr/share/java/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.pom
